name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.1.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Extract changelog for this version
        id: changelog
        run: |
          # Extract the changelog section for this version
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi

          # Use awk to extract content between version headers
          CHANGELOG=$(awk -v version="$VERSION" '
            /^## \[/ {
              if (found) exit;
              if ($0 ~ "\\[" version "\\]") {
                found=1;
                next;
              }
            }
            found && /^## \[/ { exit }
            found { print }
          ' CHANGELOG.md)

          # If no changelog found, use a default message
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="See [CHANGELOG.md](https://github.com/Oratorian/AndrewsBISUI/blob/main/CHANGELOG.md) for details."
          fi

          # Save to output (escape for multiline)
          {
            echo 'NOTES<<EOF'
            echo "$CHANGELOG"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create release archive
        run: |
          # Create a temporary directory for packaging
          mkdir -p release-temp/AndrewsBISUI

          # Copy only WoW addon files
          cp -r Ace3 release-temp/AndrewsBISUI/Ace3
          cp AndrewsBISUI.lua release-temp/AndrewsBISUI/AndrewsBISUI.lua
          cp AndrewsBISUI.toc release-temp/AndrewsBISUI/AndrewsBISUI.toc

          # List what we're about to zip (for debugging)
          echo "Contents of release archive:"
          ls -R release-temp/

          # Create the zip file - zip only the AndrewsBISUI folder
          cd release-temp
          zip -r ../AndrewsBISUI-${{ steps.get_version.outputs.VERSION }}.zip AndrewsBISUI
          cd ..

          # Verify zip contents
          echo "Zip file contents:"
          unzip -l AndrewsBISUI-${{ steps.get_version.outputs.VERSION }}.zip | head -20

      - name: Upload to CurseForge
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 1374444
          game_endpoint: wow
          game_version: 11.2.5
          file_path: AndrewsBISUI-${{ steps.get_version.outputs.VERSION }}.zip
          changelog: ${{ steps.changelog.outputs.NOTES }}
          changelog_type: markdown
          display_name: AndrewsBISUI ${{ steps.get_version.outputs.VERSION }}
          release_type: release
