name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.1.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Extract changelog for this version
        id: changelog
        run: |
          # Extract the changelog section for this version
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi

          # Use awk to extract content between version headers
          CHANGELOG=$(awk -v version="$VERSION" '
            /^## \[/ {
              if (found) exit;
              if ($0 ~ "\\[" version "\\]") {
                found=1;
                next;
              }
            }
            found && /^## \[/ { exit }
            found { print }
          ' CHANGELOG.md)

          # If no changelog found, use a default message
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="See [CHANGELOG.md](https://github.com/Oratorian/AndrewsBISUI/blob/main/CHANGELOG.md) for details."
          fi

          # Save to output (escape for multiline)
          {
            echo 'NOTES<<EOF'
            echo "$CHANGELOG"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create .pkgmeta for BigWigs packager
        run: |
          cat > .pkgmeta << 'EOF'
          package-as: AndrewsBISUI

          enable-nolib-creation: no

          ignore:
            - .github
            - .gitignore
            - api_server.py
            - requirements.txt
            - nginx-config.conf
            - setup-nginx.sh
            - "*.md"
            - CURSEFORGE_SETUP.md
            - CHANGELOG.md
            - README.md
            - .pkgmeta
          EOF

      - name: Package and Upload to CurseForge
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          args: -p 1374444 -l CHANGELOG.md
